#ifndef APP_MIU_CONFIG_H
#define APP_MIU_CONFIG_H

/* Allow ot_stateChangeCallback (app_task.c) + net_mgm_interface_state_change
 * (app_net_mgm.c) to both be registered. Default is 1, which silently drops
 * the second registration, preventing the challenge/accepted handshake. */
#define OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS 2

#define OPENTHREAD_CONFIG_LOG_LEVEL                OT_LOG_LEVEL_DEBG
#define OPENTHREAD_CONFIG_LOG_LEVEL_INIT           OT_LOG_LEVEL_NONE
#define OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE 1

#define OPENTHREAD_CONFIG_MAC_SOFTWARE_ACK_TIMEOUT_ENABLE        0
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_RETRANSMIT_ENABLE         0
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_CSMA_BACKOFF_ENABLE       0
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_TX_SECURITY_ENABLE        1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_ENERGY_SCAN_ENABLE        1
#define OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_ENABLE                0
#define OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE                       1
#define OPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE             0
#define OPENTHREAD_CONFIG_ECDSA_ENABLE                           1
#define OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE                      0
#define OPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE       0
#define OPENTHREAD_ENABLE_NCP_VENDOR_HOOK                        0
#define OPENTHREAD_PLATFORM_POSIX                                0
#define OPENTHREAD_POSIX                                         0
#define OPENTHREAD_ENABLE_VENDOR_EXTENSION                       0
#define OPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE        0
#define OPENTHREAD_CONFIG_COPROCESSOR_RPC_ENABLE                 0
#define OPENTHREAD_CONFIG_NCP_CPC_ENABLE                         0
#define OPENTHREAD_CONFIG_MAC_FILTER_ENABLE                      1
#define OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE                1
#define OPENTHREAD_CONFIG_PLATFORM_ASSERT_MANAGEMENT             1
#define OPENTHREAD_CONFIG_COMMISSIONER_ENABLE                    0
#define OPENTHREAD_CONFIG_JOINER_ENABLE                          0
#define OPENTHREAD_CONFIG_COAP_API_ENABLE                        1
#define OPENTHREAD_CONFIG_IP6_FRAGMENTATION_ENABLE               1
#define OPENTHREAD_CONFIG_NUM_MESSAGE_BUFFERS                    100
#define OPENTHREAD_CONFIG_TMF_ADDRESS_CACHE_ENTRIES              300
#define OPENTHREAD_CONFIG_MLE_MAX_CHILDREN                       64
#define OPENTHREAD_CONFIG_MLE_MAX_ROUTERS                        32
#define OPENTHREAD_CONFIG_MLE_CHILD_TIMEOUT_DEFAULT              20
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_CHECK_TIMEOUT        0
#define OPENTHREAD_CONFIG_ANNOUNCE_SENDER_ENABLE                 0
#define OPENTHREAD_CONFIG_MLE_SEND_UNICAST_ANNOUNCE_RESPONSE     0
#define OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MINIMUM_INTERVAL    6000
#define OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MAXIMUM_INTERVAL    30000
#define OPENTHREAD_CONFIG_MLE_LINK_REQUEST_MARGIN_MIN            20
#define OPENTHREAD_CONFIG_MLE_CHILD_ROUTER_LINKS                 1
#define OPENTHREAD_CONFIG_MAC_COLLISION_AVOIDANCE_DELAY_ENABLE   1
#define OPENTHREAD_CONFIG_MAC_COLLISION_AVOIDANCE_DELAY_INTERVAL 16

/*subg frequency band*/
#define OPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT         0
#define OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT         0
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_SUPPORT 1
#define OPENTHREAD_CONFIG_DEFAULT_CHANNEL                    1

#if CONFIG_SUBG_FREQUENCY_BAND_433 //433-435(spacing 500)
#define OPENTHREAD_CONFIG_CHANNEL_FREQUENCY 433000
#if CONFIG_SUBG_DATA_RATE_FSK_200K || CONFIG_SUBG_DATA_RATE_FSK_300K
#define OPENTHREAD_CONFIG_CHANNEL_SPACING                         500
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK 0x15555555
#else //50 100 150
#define OPENTHREAD_CONFIG_CHANNEL_SPACING                         250
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK 0x1fffffff
#endif
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN  1
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX  28
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE 27
#elif CONFIG_SUBG_FREQUENCY_BAND_470 //470-510(spacing 2000)
#define OPENTHREAD_CONFIG_CHANNEL_FREQUENCY                       470000
#define OPENTHREAD_CONFIG_CHANNEL_SPACING                         2000
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK 0x001fffff
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN  1
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX  20
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE 19
#elif CONFIG_SUBG_FREQUENCY_BAND_868 //863-870(spacing 500)
#define OPENTHREAD_CONFIG_CHANNEL_FREQUENCY                       863000
#define OPENTHREAD_CONFIG_CHANNEL_SPACING                         500
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK 0x00007fff
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN  1
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX  14
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE 13
#elif CONFIG_SUBG_FREQUENCY_BAND_915 //920-925(spacing 500), 915 MHZ range is (902~928), but Taiwan range is (920~925)
#define OPENTHREAD_CONFIG_CHANNEL_FREQUENCY                       920000
#define OPENTHREAD_CONFIG_CHANNEL_SPACING                         500
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MASK 0x000007ff
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MIN  1
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_MAX  10
#define OPENTHREAD_CONFIG_PLATFORM_RADIO_PROPRIETARY_CHANNEL_PAGE 9
#else
#error "Please select subg frequency band in menuconfig"
#endif

#endif /* APP_MIU_CONFIG_H */